// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// surf_descriptor
Rcpp::List surf_descriptor(const std::string file_name);
RcppExport SEXP _dlib_surf_descriptor(SEXP file_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string >::type file_name(file_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(surf_descriptor(file_name));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dlib_surf_descriptor", (DL_FUNC) &_dlib_surf_descriptor, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dlib(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
