# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Example of using dlib to extract SURF points
#' @description Example of using dlib to extract SURF points
#' @param file_name path to a bmp image
#' @return a list with the number of surf points found in the image
#' @export
surf_descriptor <- function(file_name) {
    .Call('_dlib_surf_descriptor', PACKAGE = 'dlib', file_name)
}

